In [3]:

import numpy as np

In [4]:
arr_1d=np.array([1,2,3,4])
print(arr_1d)

[1 2 3 4]


In [5]:
type(arr_1d)

numpy.ndarray

In [6]:
arr_1d.ndim


1

In [7]:
arr_2d=np.array([[1,2,5],[3,4,6]])

In [8]:
arr_2d.ndim

2

In [9]:
len(arr_1d)

4

In [10]:

arr_2d.size

6

In [11]:
len(arr_2d)

2

In [12]:
arr_2d.shape

(2, 3)

In [13]:
arr_2d.dtype


dtype('int64')

In [14]:
mx_1s=np.ones((3,4),dtype=int)

In [15]:
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [16]:
mx_0s=np.zeros((5,2),dtype=bool)
print(mx_0s)

[[False False]
 [False False]
 [False False]
 [False False]
 [False False]]


In [17]:
# NUMPYFUNCTIONS
# arange()
arr_1d=np.arange(2,21,2)
print(arr_1d)

[ 2  4  6  8 10 12 14 16 18 20]


In [18]:
# LINESPACE()  equal divide 

In [19]:
np.linspace(1,5,4,dtype=int)  #from 1 to 5 pick any 4 press shift tab to see more

array([1, 2, 3, 5])

In [20]:
# RESHSAPE()   1d to milti

In [21]:
arr_2d=arr_1d.reshape(2,5)
print(arr_2d)

[[ 2  4  6  8 10]
 [12 14 16 18 20]]


In [22]:
# Ravel() multi D to 1d

In [23]:
arr_1d=arr_2d.ravel()
print(arr_1d)

[ 2  4  6  8 10 12 14 16 18 20]


In [24]:
# Flatten () multi D to 1d  may get parameters as per need 

In [25]:
arr_1d=arr_2d.flatten()
print(arr_1d)

[ 2  4  6  8 10 12 14 16 18 20]


In [26]:
#TRANSPOSE()

In [43]:
print(arr_2d.transpose())

[[ 2 12]
 [ 4 14]
 [ 6 16]
 [ 8 18]
 [10 20]]


In [28]:
# OPERATORS

In [46]:
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
np.add(arr1,arr2)   #divide multiply subtract index to index

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [31]:
arr1.dot(arr2)    #proper matrix multiply

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [32]:
arr1.max()

np.int64(9)

In [33]:
arr1.max(axis=0) #axis0 for column axis 1 for row

array([7, 8, 9])

In [34]:
arr1.argmax()   #REturn index of maximum

np.int64(8)

In [35]:
np.sum(arr1)

np.int64(45)

In [36]:
np.sum(arr1,axis=0)  #sum of each column

array([12, 15, 18])

In [37]:
 np.mean(arr1)   #averege

np.float64(5.0)

In [38]:
np.sqrt(arr1)  #sqrt of each element

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [39]:
np.std(arr1)   #standard deviation

np.float64(2.581988897471611)

In [40]:
np.exp(arr1)  #exponent e power x

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [41]:
np.log(arr1) #natural log

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [42]:
np.log10(arr1) #log base 10

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])